source 'http://rubygems.org'                                                                                            

gem 'rails', '>= 3.0.3'
gem 'paperclip'
gem 'gravtastic'
gem 'RedCloth'
gem 'hoptoad_notifier'
gem 'haml'
gem 'mysql2' # this is the default mysql gem for rails 3. please use this as this is better than the old mysql gem
gem 'will_paginate', '>= 3.0.pre2'
gem 'ruby-debug'
gem 'feedzirra'
gem 'whenever', :require => false
gem 'jquery-rails'
gem 'hpricot'
gem 'ruby_parser'
gem 'devise'
gem 'pg'
gem 'sqlite3'

group :development, :test do
  gem 'rspec-rails'
  gem 'blueprints'
  gem 'steak'
  gem 'capybara'
  gem 'webrat'
  gem 'database_cleaner'
  gem 'spork'
  gem 'machinist'
  gem 'faker'
  gem 'email_spec'
  gem 'autotest'
  gem 'launchy'
  gem 'shoulda'
  gem 'haml-rails'
end
